create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "Anyone can submit contact messages"
on public.contact_messages;

create policy "Anyone can submit contact messages"
on public.contact_messages
for insert
to anon
with check (true);

create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  full_name text not null,
  phone text not null,
  email text not null,
  address text not null,
  age integer not null check (age between 10 and 120),
  domain text not null,
  custom_domain text,
  school_status text not null,
  school_name text,
  school_level text,
  education_level text,
  education_domain text,
  motivation text not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected'))
);

alter table public.members enable row level security;

drop policy if exists "Anyone can submit membership requests"
on public.members;

create policy "Anyone can submit membership requests"
on public.members
for insert
to anon
with check (status = 'pending');

-- No public select, update, or delete policy is created.
-- Future administration must use authenticated users and separate policies.